all:
	gcc -Wall -Werror -pedantic -o delete_node.out delete_node.c
	gcc -Wall -Werror -pedantic -o create_node.out create_node.c
	gcc -Wall -Werror -pedantic -o send.out send.c
	gcc -Wall -Werror -pedantic -o receive.out receive.c
	gcc -Wall -Werror -pedantic -o experiment.out experiment.c

clean:
	rm *.out
